---

- name: Create volumes directory
  file:
    state: directory
    path: "{{ openshift_localstorage_basedir }}"
    seuser: unconfined_u
    serole: object_r
    setype: container_file_t

- name: Create custom volumes directories
  file:
    state: directory
    path: "{{ item }}"
    seuser: unconfined_u
    serole: object_r
    setype: container_file_t
  loop: "{{ openshift_localstorage_custom_dirs }}"

- name: Template volume deployment script
  template:
    src: deploy-volumes.sh.j2
    dest: "{{ openshift_ansible_tmp }}/deploy-volumes.sh"

- name: Deploy volumes on node
  shell: "bash {{ openshift_ansible_tmp }}/deploy-volumes.sh"
